# Generated by Django 3.0.5 on 2020-12-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201201_2024'),
        ('blog', '0005_auto_20201201_2011'),
    ]

    operations = [
    ]
